# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ACTOR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': '演员',
                'verbose_name_plural': '演员',
            },
        ),
        migrations.CreateModel(
            name='COUNTRY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': '国家',
                'verbose_name_plural': '国家',
            },
        ),
        migrations.CreateModel(
            name='DIRECTOR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': '导演',
                'verbose_name_plural': '导演',
            },
        ),
        migrations.CreateModel(
            name='FILM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, unique=True, verbose_name='电影名称')),
                ('language', models.CharField(max_length=200, null=True, verbose_name='语言')),
                ('IMDb_link', models.CharField(max_length=200, null=True, verbose_name='IMDB链接')),
                ('intro', models.TextField(null=True, verbose_name='剧情介绍')),
                ('by_name', models.CharField(max_length=5000, null=True, verbose_name='链接详情')),
                ('by_link', models.CharField(max_length=5000, null=True, verbose_name='下载链接1')),
                ('pic_link', models.CharField(max_length=500, null=True, verbose_name='图片链接')),
                ('actor', models.ManyToManyField(related_name='actor_films', to='film.ACTOR', verbose_name='演员')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='film.COUNTRY', verbose_name='国家')),
                ('director', models.ManyToManyField(related_name='director_films', to='film.DIRECTOR', verbose_name='导演')),
            ],
            options={
                'verbose_name': '电影',
                'ordering': ('name',),
                'verbose_name_plural': '电影',
            },
        ),
        migrations.CreateModel(
            name='TYPE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': '类型',
                'verbose_name_plural': '类型',
            },
        ),
        migrations.CreateModel(
            name='YEAR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': '年份',
                'verbose_name_plural': '年份',
            },
        ),
        migrations.AddField(
            model_name='film',
            name='publish_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='film.YEAR', verbose_name='上映年份'),
        ),
        migrations.AddField(
            model_name='film',
            name='types',
            field=models.ManyToManyField(related_name='films', to='film.TYPE', verbose_name='类型'),
        ),
    ]
